### ISSUE TITLE
家族が分裂する

### ISSUE THREAD

**Issue by haruguchi-yuma** [sadanora/emoji-rain#1]
-e で👨‍👩‍👦 を渡すと家族が分裂します。

## 再現方法
```js
npx hiyoko-rain -e 👨‍👩‍👦
```
<img width="571" alt="image" src="https://github.com/sadanora/hiyoko-rain/assets/57053236/d98480fb-ec93-4abb-ad67-fb0db8b2127a">

**Comment by sadanora** [comment]
@haruguchi-yuma 
このissue、 lef237 さんがサッと解決してくださいました～
@lef237 さんありがとうございました！ :pray:

ちょっとした残課題を #3 に切り出して、このissueはcloseします。
